# Generated by Django 5.1.4 on 2025-02-02 08:07

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_alter_user_full_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetplan',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='budgetplan',
            name='dining',
        ),
        migrations.RemoveField(
            model_name='budgetplan',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='budgetplan',
            name='grocery',
        ),
        migrations.RemoveField(
            model_name='budgetplan',
            name='others',
        ),
        migrations.RemoveField(
            model_name='budgetplan',
            name='shopping',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.AddField(
            model_name='budgetplan',
            name='category_portion',
            field=models.JSONField(default={'Automobile': 10, 'Dining': 10, 'Gas': 10, 'Grocery': 10, 'Housing': 10, 'Medical': 10, 'Others': 20, 'Shopping': 10, 'Subscription': 10}),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01000000000000000020816681711721685132943093776702880859375'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Income', 'INCOME'), ('Housing', 'HOUSING'), ('Automobile', 'AUTO'), ('Medical', 'MEDICAL'), ('Subscription', 'SUBSCRIPTION'), ('Grocery', 'GROCERY'), ('Dining', 'FOOD & DRINK'), ('Shopping', 'SHOPPING'), ('Gas', 'GAS'), ('Others', 'OTHERS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Income', 'INCOME'), ('Housing', 'HOUSING'), ('Automobile', 'AUTO'), ('Medical', 'MEDICAL'), ('Subscription', 'SUBSCRIPTION'), ('Grocery', 'GROCERY'), ('Dining', 'FOOD & DRINK'), ('Shopping', 'SHOPPING'), ('Gas', 'GAS'), ('Others', 'OTHERS')], default='Housing', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('1'))])),
                ('due_date', models.DateField()),
                ('pay_account', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenseapp.account')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
